# Generated by Django 5.0.14 on 2025-08-20 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学员ID')),
                ('external_user_id', models.CharField(max_length=100, unique=True, verbose_name='小鹅通ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学员昵称')),
                ('alias_name', models.CharField(blank=True, max_length=100, verbose_name='备注名')),
                ('groups_json', models.TextField(default='[]', verbose_name='分组JSON')),
                ('progress_json', models.TextField(default='[]', verbose_name='学习进度JSON')),
                ('status', models.CharField(choices=[('joined', '加入'), ('active', '活跃'), ('graduated', '已毕业'), ('archived', '已归档')], default='joined', max_length=20, verbose_name='学员状态')),
                ('learning_hours', models.FloatField(default=0.0, verbose_name='累计学习时长')),
                ('research_note', models.TextField(blank=True, verbose_name='教研备注')),
                ('ops_note', models.TextField(blank=True, verbose_name='运营备注')),
                ('is_difficult', models.BooleanField(default=False, verbose_name='是否需要关注')),
                ('difficulty_source', models.CharField(blank=True, choices=[('system', '系统推送'), ('teacher', '教师推送'), ('manual', '教研选择')], max_length=50, verbose_name='困难来源')),
                ('learning_status', models.CharField(choices=[('normal', '正常学习'), ('attention', '需要关注'), ('excellent', '优秀学员'), ('new', '新学员')], default='normal', max_length=20, verbose_name='学习状态')),
                ('learning_progress', models.IntegerField(default=0, verbose_name='学习进度（课程数）')),
                ('total_study_time', models.FloatField(default=0.0, verbose_name='总学习时长')),
                ('research_notes', models.TextField(blank=True, verbose_name='教研备注（别名）')),
                ('operation_notes', models.TextField(blank=True, verbose_name='运营备注（别名）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL, verbose_name='分配教师')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'students',
                'indexes': [models.Index(fields=['student_name'], name='students_student_e48a42_idx'), models.Index(fields=['external_user_id'], name='students_externa_aedf56_idx'), models.Index(fields=['status'], name='students_status_3ac771_idx'), models.Index(fields=['learning_status'], name='students_learnin_0b530f_idx'), models.Index(fields=['is_difficult'], name='students_is_diff_b81a50_idx')],
            },
        ),
    ]
