# Generated by Django 5.0.14 on 2025-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='operation_notes',
            field=models.TextField(blank=True, default='', verbose_name='运营备注（别名）'),
        ),
        migrations.AlterField(
            model_name='student',
            name='research_notes',
            field=models.TextField(blank=True, default='', verbose_name='教研备注（别名）'),
        ),
    ]
