# Generated by Django 5.0.14 on 2025-08-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='任务ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学员昵称')),
                ('visit_count', models.IntegerField(default=0, verbose_name='回访次数')),
                ('source', models.CharField(choices=[('teacher', '教师端'), ('system', '系统规则'), ('research', '教务'), ('manual', '手动添加')], max_length=20, verbose_name='推送来源')),
                ('task_status', models.CharField(choices=[('pending', '待办'), ('contacted', '已联系'), ('no_reply', '未回复'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='待办状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='关联学员')),
            ],
            options={
                'verbose_name': '运营待办事项',
                'verbose_name_plural': '运营待办事项',
                'db_table': 'ops_tasks',
                'indexes': [models.Index(fields=['student', 'task_status'], name='ops_tasks_student_8bde4c_idx'), models.Index(fields=['source', 'created_at'], name='ops_tasks_source_5b6f0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True, verbose_name='记录ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学员昵称')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='回访时间')),
                ('visit_status', models.CharField(choices=[('pending', '待办'), ('contacted', '已联系'), ('no_reply', '未回复'), ('closed', '已关闭')], max_length=20, verbose_name='回访状态')),
                ('visit_count', models.IntegerField(verbose_name='累计回访次数')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='任课老师')),
                ('visit_note', models.TextField(verbose_name='回访记录文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学员')),
            ],
            options={
                'verbose_name': '回访记录',
                'verbose_name_plural': '回访记录',
                'db_table': 'visit_records',
                'indexes': [models.Index(fields=['student', 'visit_time'], name='visit_recor_student_f30d9c_idx'), models.Index(fields=['visit_status', 'visit_time'], name='visit_recor_visit_s_74f775_idx')],
            },
        ),
    ]
