# Generated by Django 5.0.14 on 2025-08-20 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_time', models.DateTimeField(auto_now_add=True, verbose_name='点评时间')),
                ('user_id', models.CharField(max_length=50, verbose_name='学员ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学员昵称')),
                ('progress_json', models.TextField(default='[]', verbose_name='学习进度JSON')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='回复教师姓名')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教师评语')),
                ('push_research', models.TextField(blank=True, verbose_name='推送教研备注')),
                ('push_ops', models.TextField(blank=True, verbose_name='推送运营备注')),
                ('course_name', models.CharField(blank=True, max_length=100, verbose_name='课程名称')),
                ('course_progress', models.IntegerField(default=0, verbose_name='课程进度')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学员')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教师')),
            ],
            options={
                'verbose_name': '教学反馈',
                'verbose_name_plural': '教学反馈',
                'db_table': 'feedback',
                'indexes': [models.Index(fields=['student', 'reply_time'], name='feedback_student_0933d0_idx'), models.Index(fields=['teacher', 'reply_time'], name='feedback_teacher_13c7d5_idx')],
            },
        ),
    ]
